name: IPQ60XX Build

# 工作流触发条件
on:
  workflow_dispatch:  # 手动触发
  schedule:
    # 北京时间每周五0点（UTC时间每周四16:00）
    - cron: '0 16 * * 4'

# 环境变量设置
env:
  CHIP: ipq60xx  # 芯片架构变量

# 作业定义
jobs:
  # 设置作业：从配置文件中获取设备列表
  setup:
    runs-on: ubuntu-latest
    outputs:
      devices: ${{ steps.get-devices.outputs.devices }}  # 输出设备列表
    
    steps:
    # 检出代码
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 给所有脚本文件添加执行权限
    - name: 设置脚本权限
      run: |
        chmod +x scripts/*.sh
        echo "已为所有脚本文件添加执行权限"

    # 从配置文件中获取设备列表
    - name: 获取设备列表
      id: get-devices
      run: |
        # 检查基础配置文件是否存在
        if [ ! -f "configs/${{ env.CHIP }}_base.config" ]; then
          echo "Error: configs/${{ env.CHIP }}_base.config not found!"
          echo "devices=[]" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        # 执行脚本获取设备列表
        DEVICES=$(./scripts/get-devices.sh configs/${{ env.CHIP }}_base.config)
        
        # 检查脚本执行结果
        if [ $? -ne 0 ]; then
          echo "Warning: get-devices.sh failed, using default devices"
          DEVICES='["jdcloud_re-ss-01","jdcloud_re-cs-02"]'
        fi
        
        # 输出设备列表
        echo "devices=$DEVICES" >> $GITHUB_OUTPUT
        echo "Found devices: $DEVICES"

  # 构建作业：编译固件
  build:
    needs: setup  # 依赖setup作业
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 仓库列表
        repo:
          - { url: "https://github.com/laipeng668/immortalwrt.git", branch: "master", short: "immwrt" }
          - { url: "https://github.com/laipeng668/openwrt.git", branch: "master", short: "openwrt" }
          - { url: "https://github.com/laipeng668/openwrt-6.x.git", branch: "k6.12-nss", short: "libwrt" }
        # 配置类型列表（按缓存命中率从高到低排序）
        config: ["Ultra", "Max", "Pro"]
        # 设备列表（从setup作业获取）
        device: ${{ fromJson(needs.setup.outputs.devices) }}
      max-parallel: 6  # 最大并行数
      fail-fast: false  # 不快速失败

    steps:
    # 检出代码
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 显示初始磁盘空间
    - name: 显示初始磁盘空间
      run: |
        echo "===== 初始磁盘空间 ====="
        df -h
        echo "========================="

    # 释放磁盘空间（修复后的配置）
    - name: 释放磁盘空间
      uses: jlumbroso/free-disk-space@main
      with:
        # 清理工具缓存（包括.NET、Node.js、Python等）
        tool-cache: true
        # 清理Android SDK
        android: true
        # 清理.NET SDK
        dotnet: true
        # 清理Haskell
        haskell: true
        # 清理大包（如Azure CLI、PowerShell等）
        large-packages: true
        # 清理交换空间
        swap-storage: true
        # 清理Docker镜像（如果有）
        docker-images: true

    # 显示清理后的磁盘空间
    - name: 显示清理后的磁盘空间
      run: |
        echo "===== 清理后的磁盘空间 ====="
        df -h
        echo "============================="

    # 安装编译环境
    - name: 安装编译环境
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget ccache xz-utils python3-distutils python3-pyelftools jq

    # 显示编译前系统信息
    - name: 显示编译前系统信息
      run: |
        echo "===== 编译前系统信息 ====="
        echo "## CPU信息 ##"
        lscpu | grep -E "(Model name|Architecture|CPU\(s\)|Thread|Core)"
        echo ""
        echo "## 内存信息 ##"
        free -h
        echo ""
        echo "## 磁盘空间信息 ##"
        df -h
        echo ""
        echo "## 系统负载信息 ##"
        uptime
        echo "========================="

    # 缓存配置文件
    - name: 缓存配置文件
      id: cache-config
      uses: actions/cache@v4
      with:
        path: configs/
        key: ${{ runner.os }}-config-${{ env.CHIP }}-${{ hashFiles('configs/*.config') }}
        restore-keys: |
          ${{ runner.os }}-config-${{ env.CHIP }}-

    # 缓存源码包
    - name: 缓存源码包
      id: cache-dl
      uses: actions/cache@v4
      with:
        path: dl/
        key: ${{ runner.os }}-dl-${{ matrix.repo.short }}-${{ env.CHIP }}-${{ hashFiles('feeds.conf', 'include/*') }}
        restore-keys: |
          ${{ runner.os }}-dl-${{ matrix.repo.short }}-${{ env.CHIP }}-

    # 缓存工具链
    - name: 缓存工具链
      id: cache-staging
      uses: actions/cache@v4
      with:
        path: staging_dir/
        key: ${{ runner.os }}-staging-${{ matrix.repo.short }}-${{ env.CHIP }}-${{ matrix.device }}-${{ hashFiles('.config') }}
        restore-keys: |
          ${{ runner.os }}-staging-${{ matrix.repo.short }}-${{ env.CHIP }}-${{ matrix.device }}-

    # 缓存编译缓存
    - name: 缓存编译缓存
      id: cache-ccache
      uses: actions/cache@v4
      with:
        path: .ccache/
        key: ${{ runner.os }}-ccache-${{ matrix.repo.short }}-${{ env.CHIP }}-${{ matrix.device }}-${{ matrix.config }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ matrix.repo.short }}-${{ env.CHIP }}-${{ matrix.device }}-

    # 克隆OpenWrt仓库
    - name: 克隆OpenWrt仓库
      run: |
        git clone --depth 1 --branch ${{ matrix.repo.branch }} ${{ matrix.repo.url }} openwrt
        cd openwrt
        echo "REPO_SHORT=${{ matrix.repo.short }}" >> $GITHUB_ENV

    # 添加第三方软件源
    - name: 添加第三方软件源
      run: |
        ./scripts/add-custom-feeds.sh openwrt

    # 合并配置文件
    - name: 合并配置文件
      run: |
        ./scripts/merge-configs.sh ${{ matrix.repo.short }} ${{ matrix.config }} ${{ matrix.device }} ${{ env.CHIP }}

    # 更新软件源
    - name: 更新软件源
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    # 生成配置文件
    - name: 生成配置文件
      run: |
        cd openwrt
        cp ../.config .config
        make defconfig

    # 编译固件
    - name: 编译固件
      run: |
        cd openwrt
        echo -e "$(nproc) thread build"
        make -j$(nproc) V=s || echo "Build failed with exit code $?" > ../build-error.log
        if [ -f "../build-error.log" ]; then
          cat ../build-error.log
          exit 1
        fi

    # 显示编译后系统信息
    - name: 显示编译后系统信息
      if: always()
      run: |
        echo "===== 编译后系统信息 ====="
        echo "## CPU信息 ##"
        lscpu | grep -E "(Model name|Architecture|CPU\(s\)|Thread|Core)"
        echo ""
        echo "## 内存信息 ##"
        free -h
        echo ""
        echo "## 磁盘空间信息 ##"
        df -h
        echo ""
        echo "## 系统负载信息 ##"
        uptime
        echo ""
        echo "## 编译目录大小 ##"
        if [ -d "openwrt" ]; then
          echo "OpenWrt目录大小: $(du -sh openwrt | cut -f1)"
        fi
        if [ -d "dl" ]; then
          echo "dl目录大小: $(du -sh dl | cut -f1)"
        fi
        if [ -d "staging_dir" ]; then
          echo "staging_dir目录大小: $(du -sh staging_dir | cut -f1)"
        fi
        if [ -d ".ccache" ]; then
          echo ".ccache目录大小: $(du -sh .ccache | cut -f1)"
        fi
        echo "========================="

    # 准备构建产物
    - name: 准备构建产物
      run: |
        ./scripts/rename-firmware.sh ${{ matrix.repo.short }} ${{ matrix.config }} ${{ matrix.device }} ${{ env.CHIP }}

    # 上传构建日志
    - name: 上传构建日志
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-${{ matrix.repo.short }}-${{ matrix.config }}-${{ matrix.device }}-${{ env.CHIP }}
        path: |
          openwrt/build.log
          build-error.log
        retention-days: 7

    # 上传构建产物
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ matrix.repo.short }}-${{ matrix.config }}-${{ matrix.device }}-${{ env.CHIP }}
        path: artifacts/
        retention-days: 7

  # 发布作业：创建Release
  release:
    needs: [setup, build]  # 依赖setup和build作业
    runs-on: ubuntu-latest
    # 只在定时触发或手动触发时运行
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
    # 检出代码
    - name: 检出代码
      uses: actions/checkout@v4

    # 给所有脚本文件添加执行权限
    - name: 设置脚本权限
      run: |
        chmod +x scripts/*.sh
        echo "已为所有脚本文件添加执行权限"

    # 下载所有构建产物
    - name: 下载所有构建产物
      uses: actions/download-artifact@v4
      with:
        path: artifacts/

    # 准备发布文件
    - name: 准备发布文件
      run: |
        mkdir -p release
        # 合并所有固件和配置文件
        for dir in artifacts/firmware-*; do
          if [ -d "$dir" ]; then
            cp -r "$dir"/* release/
          fi
        done
        # 合并所有配置文件
        tar -czf release/${{ env.CHIP }}-config.tar.gz -C release ${{ env.CHIP }}-config/ 2>/dev/null || true
        # 合并所有日志文件
        tar -czf release/${{ env.CHIP }}-log.tar.gz -C release ${{ env.CHIP }}-log/ 2>/dev/null || true
        # 合并所有软件包
        tar -czf release/${{ env.CHIP }}-app.tar.gz -C release ${{ env.CHIP }}-app/ 2>/dev/null || true
        # 生成发布说明
        ./scripts/generate-release-notes.sh ${{ env.CHIP }} > release/RELEASE_NOTES.md

    # 创建Release
    - name: 创建Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: $(date +%Y%m%d)-${{ env.CHIP }}
        name: ${{ env.CHIP }} Build $(date +%Y%m%d)
        body_path: release/RELEASE_NOTES.md
        files: |
          release/*.bin
          release/*.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
