name: IPQ60XX Build

# 工作流触发条件
on:
  workflow_dispatch:  # 手动触发
  schedule:
    # 北京时间每周五0点（UTC时间每周四16:00）
    - cron: '0 16 * * 4'

# 环境变量设置
env:
  CHIP: ipq60xx  # 芯片架构变量

# 作业定义
jobs:
  # 设置作业：仅动态获取设备列表
  setup:
    runs-on: ubuntu-22.04
    outputs:
      devices: ${{ steps.get-devices.outputs.devices }}  # 输出设备列表
    
    steps:
    # 检出代码
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 设置脚本权限
    - name: 设置脚本权限
      run: |
        echo "===== 设置脚本权限 ====="
        chmod +x scripts/*.sh
        echo "Setup作业: 已为所有脚本文件添加执行权限"
        echo "验证权限设置:"
        ls -la scripts/*.sh
        echo "========================="

    # 从配置文件中获取设备列表（关键步骤）
    - name: 获取设备列表
      id: get-devices
      run: |
        echo "===== 从配置文件获取设备列表 ====="
        
        # 检查基础配置文件是否存在
        if [ ! -f "configs/${{ env.CHIP }}_base.config" ]; then
          echo "错误: 配置文件 configs/${{ env.CHIP }}_base.config 不存在!"
          echo "devices=[]" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        # 验证脚本权限
        if [ ! -x "scripts/get-devices.sh" ]; then
          echo "错误: get-devices.sh 脚本没有执行权限"
          chmod +x scripts/get-devices.sh
        fi
        
        # 执行脚本获取设备列表
        echo "正在解析配置文件中的设备名称..."
        DEVICES=$(./scripts/get-devices.sh configs/${{ env.CHIP }}_base.config)
        
        # 检查脚本执行结果
        if [ $? -ne 0 ] || [ -z "$DEVICES" ]; then
          echo "警告: 无法从配置文件获取设备列表，使用默认设备"
          DEVICES='["jdcloud_re-ss-01","jdcloud_re-cs-02"]'
        fi
        
        # 输出设备列表
        echo "devices=$DEVICES" >> $GITHUB_OUTPUT
        echo "检测到的设备列表: $DEVICES"
        echo "================================"

  # 编译和打包作业
  compile-and-package:
    needs: setup  # 依赖setup作业获取设备列表
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # 按配置类型优先级排序（关键优化）
        config: ["Ultra", "Max", "Pro"]
        repo: 
          - { url: "https://github.com/laipeng668/immortalwrt.git", branch: "master", short: "immwrt" }
          - { url: "https://github.com/laipeng668/openwrt.git", branch: "master", short: "openwrt" }
          - { url: "https://github.com/laipeng668/openwrt-6.x.git", branch: "k6.12-nss", short: "libwrt" }
        # 从setup作业动态获取设备列表
        device: ${{ fromJson(needs.setup.outputs.devices) }}
      max-parallel: 6  # 最大并行数
      fail-fast: false  # 不快速失败

    steps:
    # 检出代码
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 在build作业开始时设置权限
    - name: 设置脚本权限
      run: |
        echo "===== 设置脚本权限 ====="
        chmod +x scripts/*.sh
        echo "Build作业: 已为所有脚本文件添加执行权限"
        echo "验证权限设置:"
        ls -la scripts/*.sh
        echo "========================="

    # 显示初始磁盘空间
    - name: 显示初始磁盘空间
      run: |
        echo "===== 初始磁盘空间 ====="
        df -h
        echo "========================="

    # 释放磁盘空间
    - name: 释放磁盘空间
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true
        docker-images: true

    # 显示清理后的磁盘空间
    - name: 显示清理后的磁盘空间
      run: |
        echo "===== 清理后的磁盘空间 ====="
        df -h
        echo "============================="

    # 安装编译环境（修复后的命令）
    - name: 安装编译环境
      run: |
        echo "===== 安装编译环境 ====="
        sudo apt-get update
        
        # 检查Ubuntu版本
        UBUNTU_VERSION=$(lsb_release -rs)
        echo "Ubuntu版本: $UBUNTU_VERSION"
        
        # 在Ubuntu 22.04及更高版本中，python3-distutils已被弃用
        # 直接安装python3-setuptools，它提供了相同的功能
        echo "安装Python相关依赖..."
        sudo apt-get install -y python3-setuptools
        
        # 安装其他编译依赖
        echo "安装编译工具链..."
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev rsync swig unzip zlib1g-dev file wget ccache xz-utils python3-pyelftools jq
        
        echo "验证安装..."
        python3 --version
        echo "===== 编译环境安装完成 ====="

    # 显示编译前系统信息
    - name: 显示编译前系统信息
      run: |
        echo "===== 编译前系统信息 ====="
        echo "## 当前编译任务信息 ##"
        echo "仓库: ${{ matrix.repo.short }}"
        echo "配置: ${{ matrix.config }}"
        echo "设备: ${{ matrix.device }}"
        echo ""
        echo "## CPU信息 ##"
        lscpu | grep -E "(Model name|Architecture|CPU\(s\)|Thread|Core)"
        echo ""
        echo "## 内存信息 ##"
        free -h
        echo ""
        echo "## 磁盘空间信息 ##"
        df -h
        echo ""
        echo "## 系统负载信息 ##"
        uptime
        echo "========================="

    # 缓存配置文件
    - name: 缓存配置文件
      id: cache-config
      uses: actions/cache@v4
      with:
        path: configs/
        key: ${{ runner.os }}-config-${{ env.CHIP }}-${{ hashFiles('configs/*.config') }}
        restore-keys: |
          ${{ runner.os }}-config-${{ env.CHIP }}-

    # 缓存源码包
    - name: 缓存源码包
      id: cache-dl
      uses: actions/cache@v4
      with:
        path: dl/
        key: ${{ runner.os }}-dl-${{ matrix.repo.short }}-${{ env.CHIP }}-${{ hashFiles('feeds.conf', 'include/*') }}
        restore-keys: |
          ${{ runner.os }}-dl-${{ matrix.repo.short }}-${{ env.CHIP }}-

    # 缓存工具链
    - name: 缓存工具链
      id: cache-staging
      uses: actions/cache@v4
      with:
        path: staging_dir/
        key: ${{ runner.os }}-staging-${{ matrix.repo.short }}-${{ env.CHIP }}-${{ matrix.device }}-${{ hashFiles('.config') }}
        restore-keys: |
          ${{ runner.os }}-staging-${{ matrix.repo.short }}-${{ env.CHIP }}-${{ matrix.device }}-

    # 缓存编译缓存
    - name: 缓存编译缓存
      id: cache-ccache
      uses: actions/cache@v4
      with:
        path: .ccache/
        key: ${{ runner.os }}-ccache-${{ matrix.repo.short }}-${{ env.CHIP }}-${{ matrix.device }}-${{ matrix.config }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ matrix.repo.short }}-${{ env.CHIP }}-${{ matrix.device }}-

    # 克隆OpenWrt仓库
    - name: 克隆OpenWrt仓库
      run: |
        echo "===== 克隆OpenWrt仓库
